import type { FaqDoc } from "@/server/model"

export const FAQ_GROUPS = ["Getting started", "The program", "Results and policies"] as const

export const FAQS: (Omit<FaqDoc, "id"> & { id: string })[] = [
  {
    id: "what-do-i-need",
    group: "Getting started",
    question: "What do I need?",
    subtitle: null,
    answer: [
      "A brokerage account with options trading permission (level 2).",
      "We teach on Webull, so that is our preferred platform, but we work with many different brokerages.",
      "You will also need a WhatsApp account, access to Zoom, and a minimum commitment of one quarter.",
    ],
    published: true,
    order: 1,
  },
  {
    id: "while-working",
    group: "Getting started",
    question: "Can I do this while working?",
    subtitle: null,
    answer: ["Yes. We have many members with various full-time jobs. In fact, the majority of our members are in this situation."],
    published: true,
    order: 2,
  },
  {
    id: "never-traded-options",
    group: "Getting started",
    question: "If I have never traded options in my life, can I be successful in this program?",
    subtitle: null,
    answer: [
      "Yes. We specialize in teaching people coming from the world of stocks, shorting and more.",
      "Once you begin an effective strategy of trading options, it will forever have an impact on your trading career.",
      "The education you receive becomes yours for a lifetime.",
    ],
    published: true,
    order: 3,
  },
  {
    id: "membership",
    group: "Getting started",
    question: "How does membership work?",
    subtitle: null,
    answer: [
      "Memberships run by calendar quarter: Q1 is January to March, Q2 April to June, Q3 July to September and Q4 October to December.",
      "After your intro call and enrollment, HG sets up your membership and you receive a personal invitation to create your login. There is no public sign-up.",
      "You can renew for the next quarter at any time, and your membership dates are always visible in your account.",
    ],
    published: true,
    order: 4,
  },
  {
    id: "alerts",
    group: "Getting started",
    question: "How do I get HG's alerts?",
    subtitle: null,
    answer: [
      "Buy and sell alerts appear instantly in the member area, and you can turn on notifications in your browser so you never miss one.",
      "You can also choose to receive alerts by email.",
    ],
    published: true,
    order: 5,
  },
  {
    id: "what-to-expect",
    group: "The program",
    question: "What can I expect?",
    subtitle: null,
    answer: [
      "A live classroom, 24/7.",
      "Breakout sessions as required.",
      "One-on-one sessions.",
      "Weekly Saturday presentations over Zoom.",
      "An incredible team of expert traders from around the world.",
    ],
    published: true,
    order: 6,
  },
  {
    id: "time-required",
    group: "The program",
    question: "How much time is required?",
    subtitle: null,
    answer: [
      "A mandatory Saturday beginner session from 6 to 7 PM ET, followed by all traders from 7 to 8:30 PM ET.",
      "A one-hour one-on-one session once a month.",
      "Weekly preparation time varies by student: the more you put in, the more you get out.",
      "Your specific schedule can be discussed in the onboarding session once you decide to enroll.",
    ],
    published: true,
    order: 7,
  },
  {
    id: "what-will-i-learn",
    group: "The program",
    question: "What will I learn?",
    subtitle: null,
    answer: [
      "At minimum, how to apply the principles of trading options and stocks with a system of channels and chart channels, so you enter trades at the optimal time and exit them with the largest possible growth.",
      "You will also learn proper due diligence, how to mitigate trades, and risk management.",
    ],
    published: true,
    order: 8,
  },
  {
    id: "trading-hours",
    group: "The program",
    question: "At what times can I trade options?",
    subtitle: null,
    answer: ["The options market is open from 9:30 AM until 4 PM ET, Monday through Friday, excluding stock market holidays."],
    published: true,
    order: 9,
  },
  {
    id: "returns",
    group: "Results and policies",
    question: "What kind of return can I expect?",
    subtitle: null,
    answer: [
      "We advise beginning to take profits at 30%, and we have an impressive 80% rate of trades closed green.",
      "Past results do not guarantee future results, and every trade carries risk.",
    ],
    published: true,
    order: 10,
  },
  {
    id: "sharing",
    group: "Results and policies",
    question: "Can I share the course?",
    subtitle: "With my best friend, wife, life partner, child, grandmother, uncle, sister of my mother's father's daughter?",
    answer: [
      "You can share with your husband, wife or life partner (someone at the same address). Beyond that, our content may not be shared or distributed in any way, shape or form.",
      "This is trademarked intellectual property, which prohibits the release of course data by any and all members.",
    ],
    published: true,
    order: 11,
  },
]
