import type { TestimonialDoc } from "@/server/model"

type Seed = Omit<TestimonialDoc, "id"> & { id: string }

const call = (symbol: string, strike: number, expiryLabel: string, realizedProfit: number, percentGain: number, currency = "USD") => ({
  symbol,
  type: "call" as const,
  strike,
  expiryLabel,
  realizedProfit,
  currency,
  percentGain,
})

/**
 * Member testimonials from the original site. Only obvious typos were fixed; members' words are unchanged.
 * Andrew Y.'s quote duplicated another member's word for word, so it stays hidden until his own quote is provided.
 */
export const TESTIMONIALS: Seed[] = [
  { id: "joey-d", name: "Joey D.", location: "Texas", avatar: "/media/testimonials/joey.webp", flag: null, trade: call("LMT", 490, "10/17", 2460, 0.35), quote: "HG helped me focus on trading a few powerful stocks with the best due diligence available. His options class has put me on the path to financial freedom.", published: true, order: 1 },
  { id: "jason-b", name: "Jason B.", location: "USA", avatar: "/media/testimonials/jason.webp", flag: null, trade: call("GE", 300, "10/3", 285, 0.57), quote: "HG Options takes the guesswork out of it. The path and guidance is provided, all you need to do is execute.", published: true, order: 2 },
  { id: "donnalyn-q", name: "Donnalyn Q.", location: "Maryland", avatar: "/media/testimonials/donnalyn.webp", flag: null, trade: call("SMCI", 51, "10/10", 67, 0.37), quote: "I'm blown away by my own progress in option trading! I used to be clueless, but thanks to HG Racing's insights, I'm now a trading ninja (okay, maybe not quite, but I'm definitely on the right track)! Their expert advice and encouragement have been invaluable - I'm forever grateful!", published: true, order: 3 },
  { id: "reylere", name: "Reylere", location: "China", avatar: "/media/testimonials/reylere.webp", flag: null, trade: call("PLTR", 160, "9/19", 892, 3.75), quote: "I highly recommend HG Profit Options because the mentors' specialized focus on just 20 stocks leads to a high winning ratio. The comprehensive weekly classes and one-on-one sessions prepare me with immense confidence for trading. The continuous support and clear explanations for every trade make this program exceptionally effective.", published: true, order: 4 },
  { id: "maydelis-q", name: "Maydelis Q.", location: "Florida", avatar: "/media/testimonials/maydelis.webp", flag: null, trade: call("LLY", 820, "10/17", 20772, 14.52), quote: "HG's market insights are consistently precise, blending deep analysis with flawless timing that makes complex trends feel crystal clear. As an options trading mentor, HG is exceptional, turning intricate strategies into empowering lessons that elevate every trader's skill with confidence and precision.", published: true, order: 5 },
  { id: "david-k", name: "David K.", location: "Georgia", avatar: "/media/testimonials/davidk.webp", flag: null, trade: call("RTX", 155, "9/19", 410, 1.8637), quote: "HG's insights are truly amazing and his ability to read the market is exceptional, allowing me to place a trade at the lowest point and bank it at the highest.", published: true, order: 6 },
  { id: "jimmy-m", name: "Jimmy M.", location: "Rwanda", avatar: null, flag: "RW", trade: call("IBM", 187.5, "10/17", 387.16, 0.77), quote: "HG is a legend in options trading. His market insights and stock price prediction is on point. Thank you HG for empowering me to make great trades.", published: true, order: 7 },
  { id: "david-e", name: "David E.", location: "New York", avatar: null, flag: "US", trade: call("LLY", 750, "10/17", 1315, 1.21), quote: "Learning to trade options from HG has revolutionized my trading and now I'm seeing higher percentages of profit like the above mentioned trade.", published: true, order: 8 },
  { id: "kash-n", name: "Kash N.", location: "UK", avatar: null, flag: "GB", trade: call("LMT", 480, "7/11", 1604, 4.63), quote: "The information HG gives is really valuable with deep due diligence, channel information on each stock enabling trades like this LMT Call.", published: true, order: 9 },
  { id: "andrew-b", name: "Andrew B.", location: "Canada", avatar: null, flag: "CA", trade: call("VST", 195.5, "9/19", 1760, 2), quote: "Exceptional due diligence leads to exceptional outcomes. As an example, during class Sept. 6th the 9/19 197.50 Call for VST was highlighted, noting it was due for a breakout as much as 2 channels.", published: true, order: 10 },
  { id: "evgeni-e", name: "Evgeni E.", location: "Bulgaria", avatar: null, flag: "BG", trade: call("RTX", 165, "10/10", 245, 1.06), quote: "Thanks to HG's Options Classroom my knowledge for options training has skyrocketed just as the numbers in my portfolio and trades.", published: true, order: 11 },
  { id: "joel-m", name: "Joel M.", location: "Ireland", avatar: null, flag: "IE", trade: call("VST", 197.5, "10/10", 680, 0.69), quote: "My portfolio has doubled in a matter of 4 weeks. Thanks to HG's due diligence and sharing his knowledge with the classroom.", published: true, order: 12 },
  { id: "bryan-t", name: "Bryan T.", location: "Singapore", avatar: null, flag: "SG", trade: call("PLTR", 187.5, "10/17", 1024, 0.37), quote: "Joining the Options Trading class was a game-changer for my financial journey. The course made everything easy to understand, even for a beginner. Now, I trade with discipline, see consistent growth, and make confident, informed decisions - no more guesswork or relying on tips.", published: true, order: 13 },
  { id: "toni-d", name: "Toni D.", location: "USA", avatar: null, flag: "US", trade: call("PLTR", 180, "10/10", 1086.1, 0.37), quote: "With the guidance of my mentor, I've not only grown my portfolio but also my confidence and self-assurance. His wisdom turned uncertainty into clarity, and risk into opportunity.", published: true, order: 14 },
  { id: "andrew-y", name: "Andrew Y.", location: "Texas", avatar: null, flag: "US", trade: call("PLTR", 172.5, "9/26", 1104.45, 1.04), quote: "Quote to be provided.", published: false, order: 15 },
  { id: "vikram-i", name: "Vikram I.", location: "Pennsylvania", avatar: null, flag: "US", trade: call("SMCI", 57, "10/17", 1125, 1.32), quote: "From someone who was scared of option trading and had zero knowledge, in just a month's time I have learned some good practices of the game! The group class and the 1 on 1's are so beneficial and make you feel you are going to do ok. I highly recommend HG Options!", published: true, order: 16 },
  { id: "peace-a", name: "Peace A.", location: "Kentucky", avatar: null, flag: "US", trade: call("TSM", 307.5, "10/17", 1803.6, 0.467), quote: "I started trading because a friend of mine was trading and I had no idea what I was doing. I ended up losing all my money due to lack of knowledge. Then I joined a Discord group, and I met HG, everything changed. All you need to do is follow his instructions, study diligently, and understand your channel. I promise, you'll never regret joining. Thank you HG.", published: true, order: 17 },
  { id: "suly", name: "Suly", location: "Alabama", avatar: "/media/testimonials/suly.webp", flag: null, trade: call("SMCI", 57, "10/17", 222, 1.0572), quote: "After joining HG Profit Options, I started seeing real improvement in my results. My trades are more consistent and my portfolio keeps expanding. Joining them was truly one of my best decisions.", published: true, order: 18 },
  { id: "mira-a", name: "Mira A.", location: "Ontario", avatar: "/media/testimonials/mira.webp", flag: null, trade: call("TSM", 307.5, "10/17", 1712, 0.38, "CAD"), quote: "Being just a few weeks into this journey, I am amazed at how much I have learned and grown already! The guidance and insights have helped me gain real confidence in my trades, seeing results like my recent TSM Call for a gain of $1,712 CAD feels incredibly rewarding. Feeling grateful and so excited for what's ahead!", published: true, order: 19 },
  { id: "tan-yu-jie", name: "Tan Yu Jie", location: "Singapore", avatar: "/media/testimonials/tan.webp", flag: null, trade: call("VST", 210, "10/17", 420, 0.28), quote: "My experience in HG option class has been amazing and I cannot ask for anything more. I learn about the channel, strong and soft support of a stock and the characteristic of each stock. With this information and the help of each member in the HG community I feel like I'm ahead of many people my age, 19, in terms of trading knowledge.", published: true, order: 20 },
  { id: "steve-c", name: "Steve C.", location: "New York", avatar: null, flag: "US", trade: call("GE", 310, "10/17", 488, 0.4373), quote: "Within the first month of being enrolled in HG's Profit Options Class, I was able to turn my portfolio around. With the guidance of a mentor, I got out of some bad trades, and I was able to cover all those losses with gains from HG's system in that same week. With all the support and tools I have received, I'm now trading with a clear plan and not just hoping to get lucky.", published: true, order: 21 },
]
